<?php
// Website Design page data
defined('MOODLE_INTERNAL') || die();

function local_univerziaai_get_website_design_data($assetsurl)
{
    return [
        'pagetitle' => 'Website Design Services | Custom UI/UX - UniverziaAI',
        'metadescription' => 'Professional website design services by UniverziaAI. Static, dynamic, corporate, and e-commerce website design with modern UI/UX. Get a free quote today.',
        'canonical' => $GLOBALS['CFG']->wwwroot . '/local/univerziaai/page.php?p=website_design',
        'og_image' => $assetsurl . '/website-development.png',
        'pagestyle' => '',
        'extrajs' => '
            const mobileToggle = document.getElementById("mobileToggle");
            const navMenu = document.getElementById("navMenu");
            if (mobileToggle) {
                mobileToggle.addEventListener("click", () => {
                    navMenu.classList.toggle("active");
                    mobileToggle.classList.toggle("active");
                });
            }
        ',
        'hero_title' => 'Website Design',
        'hero_subtitle' => 'We specialise in designing and developing custom websites that are tailored to our clients\' specific needs and goals. Our team has experience creating a wide range of websites, from simple blogs to complex e-commerce platforms.',
        'hero_image' => $assetsurl . '/website.jpg', // Placeholder
        'design_types' => [
            ['icon' => '<i class="fa-solid fa-file-code"></i>', 'title' => 'Static Website', 'description' => 'A static website is a type of website that consists of a set of HTML pages that remain unchanged until they are manually updated. Unlike dynamic websites, which retrieve information from a database and display it in real-time, static websites are pre-built and display the same content to all users.<br><br>One of the main benefits of a static website is its simplicity. Because they do not require a database or server-side scripting.'],
            ['icon' => '<i class="fa-solid fa-gears"></i>', 'title' => 'Dynamic Website', 'description' => 'A dynamic website is a type of website that generates content in real-time based on user interactions and data stored in a database. Unlike static websites, which display the same content to all users, dynamic websites can be customised to display different content based on the user’s location, preferences, or behaviour.<br><br>One of the main benefits of dynamic websites is their flexibility. With the ability to retrieve and display data in real-time.'],
            ['icon' => '<i class="fa-solid fa-building"></i>', 'title' => 'Corporate Websites', 'description' => 'A corporate website is a type of website that represents a business, organization, or corporation. It is designed to convey professionalism, credibility, and trust to potential customers, partners, and stakeholders.<br><br>The main goal of a corporate website is to provide information about the company, its products and services, and its values and mission.'],
            ['icon' => '<i class="fa-solid fa-cart-shopping"></i>', 'title' => 'E-Commerce Websites', 'description' => 'An e-commerce website is a type of website that allows businesses to sell products or services online. It provides a platform for businesses to reach a global audience and offer a convenient shopping experience to customers.<br><br>The main goal of an e-commerce website is to provide an easy and intuitive shopping experience for customers.'],
            ['icon' => '<i class="fa-regular fa-lightbulb"></i>', 'title' => 'Idea Based Website', 'description' => 'Idea-based website design is a process of creating a website based on a unique concept or idea. It is a creative and strategic approach to web design that focuses on communicating the essence of your brand and delivering a unique and memorable user experience.<br><br>The main goal of idea-based website design is to bring your vision to life and create a website that reflects your values, mission, and brand personality.'],
            ['icon' => '<i class="fa-solid fa-globe"></i>', 'title' => 'Web Portals', 'description' => 'A web portal is a type of website that provides a central point of access to information, resources, and tools for a specific community or audience. It is designed to streamline communication and collaboration, and to provide a one-stop destination for all the information, tools, and resources that its users need.<br><br>The main goal of a web portal is to improve the user experience and make it easier for individuals and organisations to access.'],
        ],
        'process_steps' => [
            ['icon' => '<i class="fa-solid fa-list-check"></i>', 'title' => 'Requirement Gathering', 'description' => 'Before you start designing or developing your website, it\'s important to define your objectives and goals. What do you want to achieve with your website? Who is your target audience? What type of content will you be publishing? By answering these questions, you\'ll be able to create a clear vision for your website that guides the entire design and development process.'],
            ['icon' => '<i class="fa-solid fa-magnifying-glass-chart"></i>', 'title' => 'Research and Planning', 'description' => 'Once you have a clear understanding of your objectives and goals, it\'s time to do your research. This involves studying your target audience, analysing your competition, and exploring the latest design and development trends. The information you gather during this stage will help you make informed decisions about the design, functionality and content of your website.'],
            ['icon' => '<i class="fa-solid fa-pen-ruler"></i>', 'title' => 'Wireframe Designing', 'description' => 'The next step in the process is the design and wireframing stage. During this stage, you\'ll create a visual representation of your website, including its layout, colour scheme, and typography. This stage also involves creating wireframes, which are rough sketches of each page of your website. The wireframes help you visualize the structure and hierarchy of your website.'],
            ['icon' => '<i class="fa-solid fa-code"></i>', 'title' => 'Website Development', 'description' => 'Once the design and wireframing stage is complete, it\'s time to start the development process. This involves creating the website\'s underlying code, integrating the design elements, and adding the functionalities you need to achieve your objectives and goals. This stage also includes testing and debugging to ensure that the website is functioning correctly and meets your quality standards.'],
            ['icon' => '<i class="fa-solid fa-file-pen"></i>', 'title' => 'Content Creation', 'description' => 'The next stage is content creation. This involves writing, editing, and publishing the text, images, and other media that will be featured on your website. The content you create should be engaging, informative, and optimized for search engines. This stage is also an opportunity to create a strong brand voice and style that is consistent with your objectives and goals.'],
            ['icon' => '<i class="fa-solid fa-bug-slash"></i>', 'title' => 'Testing', 'description' => 'After Completing the website we do testing of the complete website, which includes machine testing and manual testing both, we create use cases and remove the bugs where required and share final test report with the client. Testing includes Venerability testing, Cross browser website testing and device testing for website.'],
        ],
        'faq_items' => [
            ['question' => 'Why A Good Website Design Is Important For A Company', 'answer' => '<p>Website design is important for several reasons. First and foremost, a well-designed website can help to establish credibility and build trust with potential customers. When visitors come to your website, they will form an initial impression of your business based on the design and functionality of your website. A poorly designed website may give the impression that your business is unprofessional or untrustworthy.</p><p>In addition to building credibility, website designing is also important for creating a positive user experience. A website that is easy to navigate and user-friendly can help visitors find the information they need quickly and efficiently, which can improve engagement and reduce bounce rates.</p>'],
            ['question' => 'How Long Does It Take To Design A Website?', 'answer' => '<p>The time it takes to design a website can vary depending on a number of factors, such as the size and complexity of the website, the level of customization required, and the availability of content and other resources. Typically, a standard website with 5-15 pages takes around 30 days, while a more complex website with custom features and extensive content may take months to complete.</p><p>At the start of the website design process, we do requirement gathering and share a timeline with milestones. This ensures that both parties have a clear understanding of the scope and expected timeline.</p>'],
            ['question' => 'Can I See Examples Of Websites You Have Designed In The Past?', 'answer' => '<p>Yes, we understand that seeing examples of our previous work can be helpful. You can find some of our work examples in our portfolio section or request specific case studies from our sales representative.</p><p>Our portfolio includes a range of websites we’ve designed for clients in various industries.</p>'],
            ['question' => 'How Much Does UniverziaAi Charge For Website Designing?', 'answer' => '<p>The cost of website designing service depends on the scope of work. Once we understand the complete requirements, we can calculate the cost and timeline for your project. However, our starting price for website designing is INR 100,000/- (USD 1200).</p>'],
            ['question' => 'Can I Make Changes To My Website After You Handover It To Us?', 'answer' => '<p>Yes, in case of a dynamic website or a website supported by a Content Management System (CMS), you can manage the complete content of your website, which includes texts, images, videos, etc.</p>'],
        ],
    ];
}
